---
- name: aap setup for control node
  include_tasks: 10_aap_setup.yml
  tags:
    - aap_setup

- name: Install packages
  include_tasks: 15_package_dependencies.yml
  when: not pre_build|bool

- name: common workshop setup for control node
  include_tasks: 20_all_workshop.yml
  when: workshop_type is defined

- name: check to see if automation controller is already up and running
  uri:
    url: https://localhost/api/v2/ping/
    method: GET
    user: admin
    password: "{{ admin_password }}"
    validate_certs: false
    force_basic_auth: true
  register: check_controller
  ignore_errors: true
  failed_when: false
  when:
    - controllerinstall is defined
    - controllerinstall|bool

- name: install controller if knob is set
  include_tasks: "30_controller.yml"
  when:
    - controllerinstall is defined
    - controllerinstall|bool
    - check_controller.status != 200

- name: change admin password
  awx.awx.user:
    username: "admin"
    password: "{{ admin_password }}"
    state: present
    superuser: true
    controller_username: admin
    controller_password: "R3dh4t1!"
    controller_host: "https://{{ ansible_host }}"
    validate_certs: false
  when:
    - controllerinstall is defined
    - controllerinstall|bool
    - check_controller.status == 200
    - pre_build|bool

- name: Setup Route53 update service
  include_tasks: 40_route53_update.yml
  when: tower_node_aws_api_access|default(false)|bool
